import React, { useState, useEffect } from 'react';
import { initializeApp } from 'firebase/app';
import { getMessaging, getToken, onMessage } from 'firebase/messaging';
import { Bell, BellRing, Image as ImageIcon, Clock, ShieldAlert, Terminal } from 'lucide-react';

const firebaseConfig = {
  apiKey: "AIzaSyB3o2kr0PBD-LXXO_loHH_lhbBd8SrH9Pc",
    authDomain: "war-control-push.firebaseapp.com",
      projectId: "war-control-push",
        storageBucket: "war-control-push.firebasestorage.app",
          messagingSenderId: "1074882873916",
            appId: "1:1074882873916:web:24679bbdf9ce78f0329139"
            };

            const VAPID_KEY = "BBSuTkcsSNM2EDOuFwIx9sj9WVIO-B3teTIwD4nS7rOUkKl8v9SkzeZiadJMAgClf14-9-tAGrciC1rsfqINtvc";

            const app = initializeApp(firebaseConfig);
            const messaging = typeof window !== 'undefined' ? getMessaging(app) : null;

            export default function App() {
              const [token, setToken] = useState('');
                const [permission, setPermission] = useState(typeof Notification !== 'undefined' ? Notification.permission : 'default');

                  useEffect(() => {
                      if (!messaging) return;

                          const unsubscribe = onMessage(messaging, (payload) => {
                                console.log('Mensaje recibido:', payload);
                                      new Notification(payload.notification.title, {
                                              body: payload.notification.body,
                                                      icon: '/vite.svg'
                                                            });
                                                                });

                                                                    return () => unsubscribe();
                                                                      }, []);

                                                                        const requestPermission = async () => {
                                                                            try {
                                                                                  const status = await Notification.requestPermission();
                                                                                        setPermission(status);
                                                                                              if (status === 'granted') {
                                                                                                      const currentToken = await getToken(messaging, { vapidKey: VAPID_KEY });
                                                                                                              if (currentToken) {
                                                                                                                        setToken(currentToken);
                                                                                                                                }
                                                                                                                                      }
                                                                                                                                          } catch (err) {
                                                                                                                                                console.error("Error al gestionar permisos/token:", err);
                                                                                                                                                    }
                                                                                                                                                      };

                                                                                                                                                        const sendLocalNotification = (title, options) => {
                                                                                                                                                            if (permission !== 'granted') {
                                                                                                                                                                  alert("Primero debes permitir las notificaciones.");
                                                                                                                                                                        return;
                                                                                                                                                                            }
                                                                                                                                                                                
                                                                                                                                                                                    // Si estamos en un celular, podemos usar el ServiceWorkerRegistration para mostrar la notificación
                                                                                                                                                                                        // Esto asegura mayor compatibilidad en móviles Android.
                                                                                                                                                                                            if ('serviceWorker' in navigator) {
                                                                                                                                                                                                  navigator.serviceWorker.ready.then(registration => {
                                                                                                                                                                                                          registration.showNotification(title, options);
                                                                                                                                                                                                                });
                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                          new Notification(title, options);
                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                  const modes = [
                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                            id: 'instant',
                                                                                                                                                                                                                                                  title: 'Modo Directo',
                                                                                                                                                                                                                                                        desc: 'Notificación simple e inmediata',
                                                                                                                                                                                                                                                              icon: <Bell className="w-6 h-6" />,
                                                                                                                                                                                                                                                                    color: 'bg-blue-500',
                                                                                                                                                                                                                                                                          action: () => sendLocalNotification("Sistema Activo", { body: "La conexión con el servidor IDX es estable." })
                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                  {
                                                                                                                                                                                                                                                                                        id: 'urgent',
                                                                                                                                                                                                                                                                                              title: 'Modo Crítico',
                                                                                                                                                                                                                                                                                                    desc: 'Requiere atención y vibración',
                                                                                                                                                                                                                                                                                                          icon: <ShieldAlert className="w-6 h-6" />,
                                                                                                                                                                                                                                                                                                                color: 'bg-red-500',
                                                                                                                                                                                                                                                                                                                      action: () => sendLocalNotification("⚠️ ALERTA DE SEGURIDAD", { 
                                                                                                                                                                                                                                                                                                                              body: "Intento de acceso detectado en el módulo central.",
                                                                                                                                                                                                                                                                                                                                      requireInteraction: true,
                                                                                                                                                                                                                                                                                                                                              vibrate: [200, 100, 200, 100, 200, 100, 200]
                                                                                                                                                                                                                                                                                                                                                    })
                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                  id: 'media',
                                                                                                                                                                                                                                                                                                                                                                        title: 'Modo Multimedia',
                                                                                                                                                                                                                                                                                                                                                                              desc: 'Incluye previsualización de imagen',
                                                                                                                                                                                                                                                                                                                                                                                    icon: <ImageIcon className="w-6 h-6" />,
                                                                                                                                                                                                                                                                                                                                                                                          color: 'bg-emerald-500',
                                                                                                                                                                                                                                                                                                                                                                                                action: () => sendLocalNotification("Cámara Actualizada", { 
                                                                                                                                                                                                                                                                                                                                                                                                        body: "Nueva captura de la terminal de control.",
                                                                                                                                                                                                                                                                                                                                                                                                                image: "https://picsum.photos/600/300"
                                                                                                                                                                                                                                                                                                                                                                                                                      })
                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                              {
                                                                                                                                                                                                                                                                                                                                                                                                                                    id: 'delay',
                                                                                                                                                                                                                                                                                                                                                                                                                                          title: 'Modo Programado',
                                                                                                                                                                                                                                                                                                                                                                                                                                                desc: 'Retraso de 3 segundos',
                                                                                                                                                                                                                                                                                                                                                                                                                                                      icon: <Clock className="w-6 h-6" />,
                                                                                                                                                                                                                                                                                                                                                                                                                                                            color: 'bg-amber-500',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  action: () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          setTimeout(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    sendLocalNotification("Tarea Finalizada", { body: "El proceso en segundo plano terminó." });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }, 3000);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="min-h-screen bg-zinc-950 text-zinc-100 p-6 font-sans">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="max-w-2xl mx-auto space-y-8">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <header className="flex items-center justify-between">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h1 className="text-4xl font-black tracking-tighter text-white">FCM STUDIO</h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-zinc-500">Panel de Control de Notificaciones</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className={`px-4 py-1 rounded-full text-xs font-bold uppercase tracking-widest ${permission === 'granted' ? 'bg-emerald-500/10 text-emerald-500 border border-emerald-500/20' : 'bg-red-500/10 text-red-500 border border-red-500/20'}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {permission === 'granted' ? 'Conectado' : 'Sin Acceso'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </header>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {permission !== 'granted' && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="bg-indigo-600 rounded-2xl p-6 shadow-2xl shadow-indigo-500/20 flex flex-col items-center text-center space-y-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <BellRing className="w-12 h-12 text-white animate-bounce" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h2 className="text-xl font-bold text-white">Activar Notificaciones</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-indigo-100 text-sm">Para recibir alertas en tu celular, necesitamos tu permiso.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button onClick={requestPermission} className="bg-white text-indigo-600 px-8 py-3 rounded-xl font-bold hover:bg-indigo-50 transition-colors w-full sm:w-auto">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Permitir ahora
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {modes.map((mode) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          key={mode.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={mode.action}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="group bg-zinc-900 border border-zinc-800 p-5 rounded-2xl text-left hover:border-zinc-600 transition-all hover:scale-[1.02] active:scale-95 flex flex-col items-start"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className={`${mode.color} w-12 h-12 rounded-xl flex items-center justify-center mb-4 shadow-lg group-hover:rotate-12 transition-transform`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {mode.icon}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h3 className="font-bold text-lg text-white">{mode.title}</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-zinc-400 text-sm">{mode.desc}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="flex items-center gap-2 mb-4 text-zinc-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Terminal className="w-4 h-4" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="text-xs font-mono uppercase">Consola de Depuración</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <label className="text-[10px] text-zinc-500 uppercase font-bold">FCM Device Token (Para envíos desde servidor externo)</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="bg-black p-3 rounded-lg border border-zinc-800 text-[10px] font-mono text-indigo-400 break-all mt-1 min-h-[40px]">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {token || "Requiere permisos para generar token..."}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }